# Generated by Django 4.1 on 2024-02-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='team',
        ),
        migrations.AddField(
            model_name='issue',
            name='team',
            field=models.ManyToManyField(related_name='issues', to='teams.team'),
        ),
    ]
