# Generated by Django 4.1 on 2024-02-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_issue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='chatGPT_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
